version: "3.9"
services:
  mongo:
    image: mongo:5
    volumes:
      - db-mongo:/data/db
    container_name: devastation-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    
  clients:
    build: ./clients/
    container_name: devastation-clients
    volumes:
      - ./clients:/node-app
    ports:
      - 3001:3001
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_USER=admin
      - DB_PASSWORD=secret
      - CLIENTS_PORT=3001
      - FRAUDPREVENTION_HOST=fraudprevention
      - FRAUDPREVENTION_PORT=3002
      - TRANSACTIONS_HOST=transactions
      - TRANSACTIONS_PORT=3003
      - RABBIT_HOST=rabbit
      - RABBIT_PORT=5672

  fraudprevention:
    build: ./fraudPrevention/
    container_name: devastation-fraudPrevention
    volumes:
      - ./fraudPrevention:/node-app
    ports:
      - 3002:3002
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_USER=admin
      - DB_PASSWORD=secret
      - CLIENTS_HOST=clients
      - CLIENTS_PORT=3001
      - FRAUDPREVENTION_PORT=3002
      - TRANSACTIONS_HOST=transactions
      - TRANSACTIONS_PORT=3003
      - RABBIT_HOST=rabbit
      - RABBIT_PORT=5672

  transactions:
    build: ./transactions/
    container_name: devastation-transactions
    volumes:
      - ./transactions:/node-app
    ports:
      - 3003:3003
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_USER=admin
      - DB_PASSWORD=secret
      - CLIENTS_HOST=clients
      - CLIENTS_PORT=3001
      - FRAUDPREVENTION_HOST=fraudprevention
      - FRAUDPREVENTION_PORT=3002
      - TRANSACTIONS_PORT=3003
      - RABBIT_HOST=rabbit
      - RABBIT_PORT=5672

volumes:
  db-mongo:
