openapi: 3.0.3
info:
  title: DEVastation | Transaction API
  description: Transaction API for an Anti Payment Fraud Service
  version: 0.0.1
  termsOfService: https://mockapi.io
  contact:
    name: Brazil I'm DEVasted Team
    email: contato@example.com
    url: https://mockapi.io
  license:
    name: 'Lincença: GPLv3'
    url: https://www.gnu.org/licenses/gpl-3.0.html
externalDocs:
  description: Documentação burocrática
  url: https://mockapi.io
servers:
  - url: https://6096015d116f3f00174b29ba.mockapi.io/
    description: API de Teste
paths:
  /transactions:
    post:
      tags:
        - Transactions
      summary: create and validate a transaction
      security:
        - auth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                transactionValue:
                  type: number
                cardInfo:
                  type: object
                  properties:
                    number: 
                      type: string
                    name: 
                      type: string
                    expirationDate: 
                      type: string
                    cvv: 
                      type: string
                      
              
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  status:
                    type: string
                  links: 
                    type: object
                    
        '303':
          description: See Other
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  status:
                    type: string
                  links: 
                    type: object
        '401':
          description: Unauthorized
          content:
            application/json:
              example: Invalid JWT Token
        '500':
          description: Error
          content:
            application/json:
              example: Error
  /transactions/{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
    get:
      tags:
        - Transactions
      summary: fetch a transaction by id
      security:
        - auth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
    patch:
      tags:
        - Transactions
      summary: update transactions status
      security:
        - auth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
components:
  schemas:
    Transaction:
      type: object
      properties:
        id:
          type: string
        transactionValue:
          type: number
        clientId:
          type: string
        status:
          type: string
  securitySchemes:
    auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
